name: flutter_template
description: flutter template

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 网络请求客户端 https://pub.dartlang.org/packages/dio
  dio: ^2.1.13
  # dart常用工具库 https://pub.dartlang.org/packages/quiver  https://github.com/google/quiver-dart
  quiver: '>=2.0.0 <3.0.0'

  device_info: ^0.4.1+1
  package_info: ^0.4.0
  shared_preferences: ^0.5.4+6
  oktoast: ^2.2.0
  flutter_easyrefresh: ^2.0.4
  flutter_banner_swiper: ^0.1.4
  cached_network_image: ^1.1.3
  bottom_tab_bar:
    git: https://github.com/LiuC520/flutter_bottom_tab_bar.git

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 使用dart代码生成文件的库 https://pub.dartlang.org/packages/build_runner
  build_runner: any
  #https://github.com/alibaba-flutter/annotation_route
  annotation_route: any
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  #flutter packages pub run build_runner clean

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # asset_generator 根据pubspec.yaml中设置的目录模板自动向其中添加文件记录的简单脚本
  # 利用asset_generator脚本生成r.dart 资源文件,方便在代码中引用资源
  # https://github.com/flutter-dev/asset_generator
  assets:
  # assets begin
  # assets/*
    - assets/image/unselectMessage.png
    - assets/image/selectedhome.png
    - assets/image/unselectedInformation.png
    - assets/image/unselectedMe.png
    - assets/image/unselectedhome.png
    - assets/image/selectedMe.png
    - assets/image/selectMessage.png
    - assets/image/selectedInformation.png
  # assets end

